displayName: SSI Processor
type: middleware

import: github.com/detharhtun/traefik-ssi-plugin

summary: 'Server Side Includes (SSI) processor for Traefik'

testData:
  rootPath: /var/www/html
  extensions:
    - .shtml
    - .html
  enableVirtual: true